/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MentalModelSearchResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MentalModelSearchResponse{}

// MentalModelSearchResponse struct for MentalModelSearchResponse
type MentalModelSearchResponse struct {
	Items []MentalModelSearchResult `json:"items"`
}

type _MentalModelSearchResponse MentalModelSearchResponse

// NewMentalModelSearchResponse instantiates a new MentalModelSearchResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMentalModelSearchResponse(items []MentalModelSearchResult) *MentalModelSearchResponse {
	this := MentalModelSearchResponse{}
	this.Items = items
	return &this
}

// NewMentalModelSearchResponseWithDefaults instantiates a new MentalModelSearchResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMentalModelSearchResponseWithDefaults() *MentalModelSearchResponse {
	this := MentalModelSearchResponse{}
	return &this
}

// GetItems returns the Items field value
func (o *MentalModelSearchResponse) GetItems() []MentalModelSearchResult {
	if o == nil {
		var ret []MentalModelSearchResult
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *MentalModelSearchResponse) GetItemsOk() ([]MentalModelSearchResult, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *MentalModelSearchResponse) SetItems(v []MentalModelSearchResult) {
	o.Items = v
}

func (o MentalModelSearchResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MentalModelSearchResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *MentalModelSearchResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMentalModelSearchResponse := _MentalModelSearchResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMentalModelSearchResponse)

	if err != nil {
		return err
	}

	*o = MentalModelSearchResponse(varMentalModelSearchResponse)

	return err
}

type NullableMentalModelSearchResponse struct {
	value *MentalModelSearchResponse
	isSet bool
}

func (v NullableMentalModelSearchResponse) Get() *MentalModelSearchResponse {
	return v.value
}

func (v *NullableMentalModelSearchResponse) Set(val *MentalModelSearchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableMentalModelSearchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableMentalModelSearchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMentalModelSearchResponse(val *MentalModelSearchResponse) *NullableMentalModelSearchResponse {
	return &NullableMentalModelSearchResponse{value: val, isSet: true}
}

func (v NullableMentalModelSearchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMentalModelSearchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
