/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.9.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SearchMentalModelsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SearchMentalModelsRequest{}

// SearchMentalModelsRequest Semantic mental-model search request for latency-sensitive consumers.
type SearchMentalModelsRequest struct {
	Query string `json:"query"`
	MaxResults *int32 `json:"max_results,omitempty"`
	MaxTokens *int32 `json:"max_tokens,omitempty"`
	MinRelevance NullableFloat32 `json:"min_relevance,omitempty"`
	Tags []string `json:"tags,omitempty"`
	TagsMatch *string `json:"tags_match,omitempty"`
}

type _SearchMentalModelsRequest SearchMentalModelsRequest

// NewSearchMentalModelsRequest instantiates a new SearchMentalModelsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSearchMentalModelsRequest(query string) *SearchMentalModelsRequest {
	this := SearchMentalModelsRequest{}
	this.Query = query
	var maxResults int32 = 3
	this.MaxResults = &maxResults
	var maxTokens int32 = 2048
	this.MaxTokens = &maxTokens
	var tagsMatch string = "any"
	this.TagsMatch = &tagsMatch
	return &this
}

// NewSearchMentalModelsRequestWithDefaults instantiates a new SearchMentalModelsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSearchMentalModelsRequestWithDefaults() *SearchMentalModelsRequest {
	this := SearchMentalModelsRequest{}
	var maxResults int32 = 3
	this.MaxResults = &maxResults
	var maxTokens int32 = 2048
	this.MaxTokens = &maxTokens
	var tagsMatch string = "any"
	this.TagsMatch = &tagsMatch
	return &this
}

// GetQuery returns the Query field value
func (o *SearchMentalModelsRequest) GetQuery() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Query
}

// GetQueryOk returns a tuple with the Query field value
// and a boolean to check if the value has been set.
func (o *SearchMentalModelsRequest) GetQueryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Query, true
}

// SetQuery sets field value
func (o *SearchMentalModelsRequest) SetQuery(v string) {
	o.Query = v
}

// GetMaxResults returns the MaxResults field value if set, zero value otherwise.
func (o *SearchMentalModelsRequest) GetMaxResults() int32 {
	if o == nil || IsNil(o.MaxResults) {
		var ret int32
		return ret
	}
	return *o.MaxResults
}

// GetMaxResultsOk returns a tuple with the MaxResults field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchMentalModelsRequest) GetMaxResultsOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxResults) {
		return nil, false
	}
	return o.MaxResults, true
}

// HasMaxResults returns a boolean if a field has been set.
func (o *SearchMentalModelsRequest) HasMaxResults() bool {
	if o != nil && !IsNil(o.MaxResults) {
		return true
	}

	return false
}

// SetMaxResults gets a reference to the given int32 and assigns it to the MaxResults field.
func (o *SearchMentalModelsRequest) SetMaxResults(v int32) {
	o.MaxResults = &v
}

// GetMaxTokens returns the MaxTokens field value if set, zero value otherwise.
func (o *SearchMentalModelsRequest) GetMaxTokens() int32 {
	if o == nil || IsNil(o.MaxTokens) {
		var ret int32
		return ret
	}
	return *o.MaxTokens
}

// GetMaxTokensOk returns a tuple with the MaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchMentalModelsRequest) GetMaxTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxTokens) {
		return nil, false
	}
	return o.MaxTokens, true
}

// HasMaxTokens returns a boolean if a field has been set.
func (o *SearchMentalModelsRequest) HasMaxTokens() bool {
	if o != nil && !IsNil(o.MaxTokens) {
		return true
	}

	return false
}

// SetMaxTokens gets a reference to the given int32 and assigns it to the MaxTokens field.
func (o *SearchMentalModelsRequest) SetMaxTokens(v int32) {
	o.MaxTokens = &v
}

// GetMinRelevance returns the MinRelevance field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchMentalModelsRequest) GetMinRelevance() float32 {
	if o == nil || IsNil(o.MinRelevance.Get()) {
		var ret float32
		return ret
	}
	return *o.MinRelevance.Get()
}

// GetMinRelevanceOk returns a tuple with the MinRelevance field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchMentalModelsRequest) GetMinRelevanceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MinRelevance.Get(), o.MinRelevance.IsSet()
}

// HasMinRelevance returns a boolean if a field has been set.
func (o *SearchMentalModelsRequest) HasMinRelevance() bool {
	if o != nil && o.MinRelevance.IsSet() {
		return true
	}

	return false
}

// SetMinRelevance gets a reference to the given NullableFloat32 and assigns it to the MinRelevance field.
func (o *SearchMentalModelsRequest) SetMinRelevance(v float32) {
	o.MinRelevance.Set(&v)
}
// SetMinRelevanceNil sets the value for MinRelevance to be an explicit nil
func (o *SearchMentalModelsRequest) SetMinRelevanceNil() {
	o.MinRelevance.Set(nil)
}

// UnsetMinRelevance ensures that no value is present for MinRelevance, not even an explicit nil
func (o *SearchMentalModelsRequest) UnsetMinRelevance() {
	o.MinRelevance.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SearchMentalModelsRequest) GetTags() []string {
	if o == nil {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SearchMentalModelsRequest) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *SearchMentalModelsRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *SearchMentalModelsRequest) SetTags(v []string) {
	o.Tags = v
}

// GetTagsMatch returns the TagsMatch field value if set, zero value otherwise.
func (o *SearchMentalModelsRequest) GetTagsMatch() string {
	if o == nil || IsNil(o.TagsMatch) {
		var ret string
		return ret
	}
	return *o.TagsMatch
}

// GetTagsMatchOk returns a tuple with the TagsMatch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SearchMentalModelsRequest) GetTagsMatchOk() (*string, bool) {
	if o == nil || IsNil(o.TagsMatch) {
		return nil, false
	}
	return o.TagsMatch, true
}

// HasTagsMatch returns a boolean if a field has been set.
func (o *SearchMentalModelsRequest) HasTagsMatch() bool {
	if o != nil && !IsNil(o.TagsMatch) {
		return true
	}

	return false
}

// SetTagsMatch gets a reference to the given string and assigns it to the TagsMatch field.
func (o *SearchMentalModelsRequest) SetTagsMatch(v string) {
	o.TagsMatch = &v
}

func (o SearchMentalModelsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SearchMentalModelsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["query"] = o.Query
	if !IsNil(o.MaxResults) {
		toSerialize["max_results"] = o.MaxResults
	}
	if !IsNil(o.MaxTokens) {
		toSerialize["max_tokens"] = o.MaxTokens
	}
	if o.MinRelevance.IsSet() {
		toSerialize["min_relevance"] = o.MinRelevance.Get()
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.TagsMatch) {
		toSerialize["tags_match"] = o.TagsMatch
	}
	return toSerialize, nil
}

func (o *SearchMentalModelsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"query",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSearchMentalModelsRequest := _SearchMentalModelsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSearchMentalModelsRequest)

	if err != nil {
		return err
	}

	*o = SearchMentalModelsRequest(varSearchMentalModelsRequest)

	return err
}

type NullableSearchMentalModelsRequest struct {
	value *SearchMentalModelsRequest
	isSet bool
}

func (v NullableSearchMentalModelsRequest) Get() *SearchMentalModelsRequest {
	return v.value
}

func (v *NullableSearchMentalModelsRequest) Set(val *SearchMentalModelsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSearchMentalModelsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSearchMentalModelsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSearchMentalModelsRequest(val *SearchMentalModelsRequest) *NullableSearchMentalModelsRequest {
	return &NullableSearchMentalModelsRequest{value: val, isSet: true}
}

func (v NullableSearchMentalModelsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSearchMentalModelsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
